### ISSUE TITLE
Cannot install the CRX chrome extension

### ISSUE THREAD

**Issue by peter-wan-intuit** [intuit/ReplayWeb#20]
### Environment
macOS 10.13.6
Chrome Version 77.0.3865.120
https://github.com/intuit/ReplayWeb/releases/tag/v1.0.0

### Actual Behavior

CRX_REQUIRED_PROOF_MISSING error

### Desired Behavior

Installed chrome extension

### Steps to Reproduce

- Open chrome tab to chrome://extensions/ and enabled Developer mode
- Dragging and dropping the downloaded crx file to browser tab from Finder 
- "Continue" on security message warning that extensions can be harmful:
![image](https://user-images.githubusercontent.com/45797988/66959764-ec435980-f01f-11e9-83ed-44832fd6dddd.png)
- See error:
![image](https://user-images.githubusercontent.com/45797988/66959800-fe24fc80-f01f-11e9-994a-d9b95efdb030.png)

**Comment by 20harshita** [comment]
Can i looking into this issue ?

**Comment by rahulkshinde** [comment]
@peter-wan-intuit Fix was released in https://github.com/intuit/ReplayWeb/releases/tag/v1.0.1

**Comment by peter-wan-intuit** [comment]
Verified 👍
