### ISSUE TITLE
Failing tests because of unresolved module '@replayweb/utils'

### ISSUE THREAD

**Issue by samrae7** [intuit/ReplayWeb#35]
### Actual Behavior

Clone repo and run 'yarn` then `yarn test`

I see 17 failing tests, all with variations of the following error

```
  ● Test suite failed to run

    Cannot find module '@replayweb/utils' from 'command_runner.js'

    However, Jest was able to find:
    	'../../src/command_runner.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    > 1 | import {
        | ^
      2 |   regExpMatch,
      3 |   replaceAllFields,
      4 |   traverseJson,

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (packages/testrunner/src/command_runner.js:1:1)
```
### Desired Behavior

The path to '@replayweb/utils' should be resolved and the tests should pass

### Steps to Reproduce
npm version 6.4.1
node version 10.15.0
yarn version 1.13.0
Clone repo and run 'yarn` then `yarn test`

**Comment by Celeo** [comment]
Give this a try:

1. Clone
1. `yarn`
1. `yarn lerna bootstrap`
1. `yarn lerna run build`
1. `yarn test`

**Comment by samrae7** [comment]
hey thanks @Celeo I'll try this asap. Assuming it works I will submit a PR to enhance the docs to make this clearer/more prominent.

**Comment by samrae7** [comment]
Thanks @Celeo this worked. Does this change to the README cover it?:
https://github.com/intuit/ReplayWeb/commit/811199010fe7762d09f61619468c3846d4c4dcca#diff-8cc7b2b0d78dd2501610391c086a8516
?

I ran your steps before I saw that change. Not sure if just running `yarn build` would have achieved the same thing (I tried removing `target` directory and `node_modules` to replicate my issue and test it out but now the tests are still passing after just running yarn)

UPDATE- just saw that `yarn build` is aliased to `lerna run build` in tha package.json. So the only thing that might be missing is to run `yarn lerna bootstrap`

**Comment by Celeo** [comment]
Yup, I'd say that step (2) here: https://github.com/intuit/ReplayWeb/blob/master/.github/CONTRIBUTING.md#development-flow should either be: `lerna bootstrap` _or_ `yarn && yarn lerna bootstrap` (for folks that don't have lerna installed globally).
