### ISSUE TITLE
Open contributions welcome - adding tests

### ISSUE THREAD

**Issue by Celeo** [intuit/ReplayWeb#5]
Testing is a great way to get into a new project! While many can see it as a not-so-glamorous way of contributing, it's a great way to dive in, as there are plenty of examples to follow.

We're happy to receive any contributions to the project in the form of additional unit tests. Many files that have room for improvement have _some_ tests already defined, so getting started there should be easy!

If you have help, feel free to ask here, or open another issue specifically for what you're seeing and label it with "internal api".

Thanks for contributing!

**Comment by AnupKumarGupta** [comment]
@Celeo I want to work on this issue

**Comment by Celeo** [comment]
@AnupKumarGupta Sure: pick a file, see the similar existing tests, and have at it!.

**Comment by stpalmer21** [comment]
This sounds awesome! Can't wait to contribute

**Comment by Hank-TNguyen** [comment]
I'd love to help with this too

**Comment by reubenae** [comment]
I've added some tests in a PR, and while I know test coverage is always helpful, I'd love to direct it where you think its most important. Could you add your top priority files to this issue?

**Comment by Celeo** [comment]
We're still happy to receive contributions in the form of additional tests, but I've closed this as Hacktoberfest is over. Thank you to everyone who contributed!
